export function compactMedicalAbbreviations(value: string) {
  return String(value ?? "")
    .replace(/\bvital signs?\b/gi, "V/S")
    .replace(/\bblood pressure\b/gi, "BP")
    .replace(/\btemperature\b/gi, "T")
    .replace(/\brespiratory rate\b/gi, "RR")
    .replace(/\boxygen saturation\b/gi, "SpO2")
    .replace(/\boxygen requirement\b/gi, "O2 req")
    .replace(/\boxygen\b/gi, "O2")
    .replace(/\bnasal cannula\b/gi, "NC")
    .replace(/\broom air\b/gi, "RA")
    .replace(/\bcomputed tomography\b/gi, "CT")
    .replace(/\bmagnetic resonance imaging\b/gi, "MRI")
    .replace(/\bchest\s+x[- ]?ray\b/gi, "CXR")
    .replace(/\bultrasound\b/gi, "U/S")
    .replace(/\bupper endoscopy\b/gi, "EGD")
    .replace(/\bantibiotics?\b/gi, "Abx")
    .replace(/\bantimicrobials?\b/gi, "Abx")
    .replace(/\bblood cultures?\b/gi, "B/C")
    .replace(/\burine cultures?\b/gi, "U/C")
    .replace(/\bsputum cultures?\b/gi, "Sputum Cx")
    .replace(/\bcultures?\b/gi, "Cx")
    .replace(/\bfollow[- ]?up\b/gi, "f/u")
    .replace(/\bcontinue(?:d|s|ing)?\b/gi, "cont")
    .replace(/\bwithout\b/gi, "w/o")
    .replace(/\bwith\b/gi, "w/")
    .replace(/\bstatus post\b/gi, "s/p")
    .replace(/\bconcern for\b/gi, "c/f")
    .replace(/\brule out\b/gi, "r/o")
    .replace(/\bpneumonia\b/gi, "PNA")
    .replace(/\burinary tract infection\b/gi, "UTI")
    .replace(/\bacute kidney injury\b/gi, "AKI")
    .replace(/\bchronic kidney disease\b/gi, "CKD")
    .replace(/\bend[- ]stage renal disease\b/gi, "ESRD")
    .replace(/\bhemodialysis\b/gi, "HD")
    .replace(/\brespiratory failure\b/gi, "RF")
    .replace(/\bcongestive heart failure\b/gi, "CHF")
    .replace(/\bheart failure\b/gi, "HF")
    .replace(/\batrial fibrillation\b/gi, "AF")
    .replace(/\bcoronary artery disease\b/gi, "CAD")
    .replace(/\bdiabetes mellitus\b/gi, "DM")
    .replace(/\bhypertension\b/gi, "HTN")
    .replace(/\bchronic obstructive pulmonary disease\b/gi, "COPD")
    .replace(/\boutpatient department\b/gi, "OPD")
    .replace(/\boutpatient clinic\b/gi, "OPD")
    .replace(/\bclinic f\/u\b/gi, "OPD f/u")
    .replace(/\bdiagnosis certificate\b/gi, "Cert")
    .replace(/\bcertificate\b/gi, "Cert")
    .replace(/\bdischarge\b/gi, "DC")
    .replace(/\bdiscontinued\b/gi, "d/c'd")
    .replace(/\bdiscontinue(?:s)?\b/gi, "d/c")
    .replace(/\s+/g, " ")
    .trim();
}
